server:
  port: 8084
  forward-headers-strategy: framework

spring:
  application:
    name: document-service
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

feign:
  clients:
    account:
      url: ${ACCOUNT_SERVICE_URL}
    hospital:
      url: ${HOSPITAL_SERVICE_URL}

elasticsearch:
  hostAndPort: ${ELASTICSEARCH_HOST_AND_PORT}

base:
  locale: ${DEFAULT_LOCALE}
  min-offset: ${MIN_OFFSET}
  min-limit: ${MIN_LIMIT}
  max-limit: ${MAX_LIMIT}