
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql
security:
  jwt:
    access-secret: ${JWT_ACCESS_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
server:
  port: 8081
  forward-headers-strategy: framework
base:
  locale: ${DEFAULT_LOCALE}
  min-offset: ${MIN_OFFSET}
  min-limit: ${MIN_LIMIT}
  max-limit: ${MAX_LIMIT}